In [113]:
import pandas as pd
import numpy as np
from datetime import datetime 

fs = pd.read_csv('flights_sample_3m.csv')

fs.info()
fs.isna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 32 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   FL_DATE                  1048575 non-null  object
 1   AIRLINE                  1048575 non-null  object
 2   AIRLINE_DOT              1048575 non-null  object
 3   AIRLINE_CODE             1048575 non-null  object
 4   DOT_CODE                 1048575 non-null  int64
 5   FL_NUMBER                1048575 non-null  int64
 6   ORIGIN                   1048575 non-null  object
 7   ORIGIN_CITY              1048575 non-null  object
 8   DEST                     1048575 non-null  object
 9   DEST_CITY                1048575 non-null  object
 10  CRS_DEP_TIME             1048575 non-null  int64
 11  DEP_TIME                 1021527 non-null  float64
 12  DEP_DELAY                1021518 non-null  float64
 13  TAXI_OUT                 1021103 non-null  float64
 14  WHEELS_OFF               1021103 non-null  float64
 15  WHEELS_ON                1020709 non-null  float64
 16  TAXI_IN                  1020709 non-null  float64
 17  CRS_ARR_TIME             1048575 non-null  int64
 18  ARR_TIME                 1020709 non-null  float64
 19  ARR_DELAY                1018570 non-null  float64
 20  CANCELLED                1048575 non-null  int64
 21  CANCELLATION_CODE        27597 non-null    object
 22  DIVERTED                 1048575 non-null  int64
 23  CRS_ELAPSED_TIME         1048568 non-null  float64
 24  ELAPSED_TIME             1018570 non-null  float64
 25  AIR_TIME                 1018570 non-null  float64
 26  DISTANCE                 1048575 non-null  int64
 27  DELAY_DUE_CARRIER        187272 non-null   float64
 28  DELAY_DUE_WEATHER        187272 non-null   float64
 29  DELAY_DUE_NAS            187272 non-null   float64
 30  DELAY_DUE_SECURITY       187272 non-null   float64
 31  DELAY_DUE_LATE_AIRCRAFT  187272 non-null   float64
dtypes: float64(16), int64(7), object(9)
memory usage: 256.0+ MB

FL_DATE                          0
AIRLINE                          0
AIRLINE_DOT                      0
AIRLINE_CODE                     0
DOT_CODE                         0
FL_NUMBER                        0
ORIGIN                           0
ORIGIN_CITY                      0
DEST                             0
DEST_CITY                        0
CRS_DEP_TIME                     0
DEP_TIME                     27048
DEP_DELAY                    27057
TAXI_OUT                     27472
WHEELS_OFF                   27472
WHEELS_ON                    27866
TAXI_IN                      27866
CRS_ARR_TIME                     0
ARR_TIME                     27866
ARR_DELAY                    30005
CANCELLED                        0
CANCELLATION_CODE          1020978
DIVERTED                         0
CRS_ELAPSED_TIME                 7
ELAPSED_TIME                 30005
AIR_TIME                     30005
DISTANCE                         0
DELAY_DUE_CARRIER           861303
DELAY_DUE_WEATHER           861303
DELAY_DUE_NAS               861303
DELAY_DUE_SECURITY          861303
DELAY_DUE_LATE_AIRCRAFT     861303
dtype: int64

In [114]:
import pandas as pd

# Assuming 'fs' is your DataFrame
# Create a mask to filter rows where at least one of the columns has a nonzero and non-null value
mask = (
    (fs['DELAY_DUE_CARRIER'].notnull() & fs['DELAY_DUE_CARRIER'] != 0) | 
    (fs['DELAY_DUE_WEATHER'].notnull() & fs['DELAY_DUE_WEATHER'] != 0)
)

# Add additional conditions to ensure 'DELAY_DUE_NAS', 'DELAY_DUE_SECURITY', and 'DELAY_DUE_LATE_AIRCRAFT' are either 0 or null
mask &= (
    (fs['DELAY_DUE_NAS'].isnull() | (fs['DELAY_DUE_NAS'] == 0)) &
    (fs['DELAY_DUE_SECURITY'].isnull() | (fs['DELAY_DUE_SECURITY'] == 0)) &
    (fs['DELAY_DUE_LATE_AIRCRAFT'].isnull() | (fs['DELAY_DUE_LATE_AIRCRAFT'] == 0))
)

# Apply the mask to filter the DataFrame
fs = fs[mask]

fs.head(20)

,FL_DATE,AIRLINE,AIRLINE_DOT,AIRLINE_CODE,DOT_CODE,FL_NUMBER,ORIGIN,ORIGIN_CITY,DEST,DEST_CITY,...,DIVERTED,CRS_ELAPSED_TIME,ELAPSED_TIME,AIR_TIME,DISTANCE,DELAY_DUE_CARRIER,DELAY_DUE_WEATHER,DELAY_DUE_NAS,DELAY_DUE_SECURITY,DELAY_DUE_LATE_AIRCRAFT
5,2019-07-31,Southwest Airlines Co.,Southwest Airlines Co.: WN,WN,19393,665,DAL,"Dallas, TX",OKC,"Oklahoma City, OK",...,0,60.0,54.0,36.0,181,141.0,0.0,0.0,0.0,0.0
10,2021-06-11,Delta Air Lines Inc.,Delta Air Lines Inc.: DL,DL,19790,2820,ATL,"Atlanta, GA",BDL,"Hartford, CT",...,0,142.0,133.0,115.0,859,60.0,0.0,0.0,0.0,0.0
37,2019-07-18,Southwest Airlines Co.,Southwest Airlines Co.: WN,WN,19393,992,IND,"Indianapolis, IN",TPA,"Tampa, FL",...,0,135.0,113.0,104.0,837,57.0,0.0,0.0,0.0,0.0
62,2019-02-27,Southwest Airlines Co.,Southwest Airlines Co.: WN,WN,19393,760,MDW,"Chicago, IL",MHT,"Manchester, NH",...,0,125.0,113.0,94.0,838,31.0,0.0,0.0,0.0,0.0
97,2019-12-01,Delta Air Lines Inc.,Delta Air Lines Inc.: DL,DL,19790,1950,MCO,"Orlando, FL",LGA,"New York, NY",...,0,155.0,152.0,120.0,950,20.0,0.0,0.0,0.0,0.0
125,2022-07-09,JetBlue Airways,JetBlue Airways: B6,B6,20409,1447,HPN,"White Plains, NY",TPA,"Tampa, FL",...,0,181.0,180.0,147.0,1032,110.0,0.0,0.0,0.0,0.0
128,2023-06-19,United Air Lines Inc.,United Air Lines Inc.: UA,UA,19977,323,EWR,"Newark, NJ",ORD,"Chicago, IL",...,0,154.0,136.0,107.0,719,22.0,0.0,0.0,0.0,0.0
158,2021-11-19,Southwest Airlines Co.,Southwest Airlines Co.: WN,WN,19393,3080,BNA,"Nashville, TN",MDW,"Chicago, IL",...,0,95.0,81.0,64.0,395,78.0,0.0,0.0,0.0,0.0
208,2021-01-02,Southwest Airlines Co.,Southwest Airlines Co.: WN,WN,19393,1099,DEN,"Denver, CO",FLL,"Fort Lauderdale, FL",...,0,225.0,218.0,202.0,1703,35.0,0.0,0.0,0.0,0.0
217,2019-09-14,Alaska Airlines Inc.,Alaska Airlines Inc.: AS,AS,19930,500,SEA,"Seattle, WA",IND,"Indianapolis, IN",...,0,255.0,240.0,205.0,1866,16.0,0.0,0.0,0.0,0.0
220,2023-07-03,Spirit Air Lines,Spirit Air Lines: NK,NK,20416,356,MCO,"Orlando, FL",IAH,"Houston, TX",...,0,148.0,140.0,116.0,854,38.0,0.0,0.0,0.0,0.0
239,2022-05-18,Delta Air Lines Inc.,Delta Air Lines Inc.: DL,DL,19790,1615,RDU,"Raleigh/Durham, NC",ATL,"Atlanta, GA",...,0,90.0,83.0,57.0,356,30.0,0.0,0.0,0.0,0.0
269,2021-06-03,SkyWest Airlines Inc.,SkyWest Airlines Inc.: OO,OO,20304,5141,DEN,"Denver, CO",SGU,"St. George, UT",...,0,96.0,102.0,75.0,517,110.0,0.0,0.0,0.0,0.0
320,2023-03-04,Delta Air Lines Inc.,Delta Air Lines Inc.: DL,DL,19790,540,BOS,"Boston, MA",ATL,"Atlanta, GA",...,0,188.0,165.0,146.0,946,0.0,39.0,0.0,0.0,0.0
321,2021-04-12,Delta Air Lines Inc.,Delta Air Lines Inc.: DL,DL,19790,985,DCA,"Washington, DC",JFK,"New York, NY",...,0,93.0,83.0,42.0,213,24.0,0.0,0.0,0.0,0.0
323,2019-11-29,Mesa Airlines Inc.,Mesa Airlines Inc.: YV,YV,20378,6096,IAH,"Houston, TX",OKC,"Oklahoma City, OK",...,0,95.0,103.0,70.0,395,17.0,0.0,0.0,0.0,0.0
362,2023-01-11,Hawaiian Airlines Inc.,Hawaiian Airlines Inc.: HA,HA,19690,45,SJC,"San Jose, CA",OGG,"Kahului, HI",...,0,340.0,372.0,344.0,2355,32.0,14.0,0.0,0.0,0.0
364,2021-10-05,Delta Air Lines Inc.,Delta Air Lines Inc.: DL,DL,19790,2510,ATL,"Atlanta, GA",IND,"Indianapolis, IN",...,0,86.0,85.0,72.0,432,0.0,104.0,0.0,0.0,0.0
381,2022-12-23,Horizon Air,Horizon Air: QX,QX,19687,2405,ANC,"Anchorage, AK",FAI,"Fairbanks, AK",...,0,69.0,68.0,51.0,261,0.0,19.0,0.0,0.0,0.0
386,2021-10-10,SkyWest Airlines Inc.,SkyWest Airlines Inc.: OO,OO,20304,3619,ORD,"Chicago, IL",DTW,"Detroit, MI",...,0,77.0,71.0,45.0,235,0.0,39.0,0.0,0.0,0.0

In [115]:
#removing missing values
fs= fs.dropna()

fs.isna().sum()

FL_DATE                    0.0
AIRLINE                    0.0
AIRLINE_DOT                0.0
AIRLINE_CODE               0.0
DOT_CODE                   0.0
FL_NUMBER                  0.0
ORIGIN                     0.0
ORIGIN_CITY                0.0
DEST                       0.0
DEST_CITY                  0.0
CRS_DEP_TIME               0.0
DEP_TIME                   0.0
DEP_DELAY                  0.0
TAXI_OUT                   0.0
WHEELS_OFF                 0.0
WHEELS_ON                  0.0
TAXI_IN                    0.0
CRS_ARR_TIME               0.0
ARR_TIME                   0.0
ARR_DELAY                  0.0
CANCELLED                  0.0
CANCELLATION_CODE          0.0
DIVERTED                   0.0
CRS_ELAPSED_TIME           0.0
ELAPSED_TIME               0.0
AIR_TIME                   0.0
DISTANCE                   0.0
DELAY_DUE_CARRIER          0.0
DELAY_DUE_WEATHER          0.0
DELAY_DUE_NAS              0.0
DELAY_DUE_SECURITY         0.0
DELAY_DUE_LATE_AIRCRAFT    0.0
dtype: float64

In [116]:
#removing cancelled flights
pd.Series(fs["CANCELLED"] == 1).sum()

#all deleted from deleting rows with no values

0

In [117]:
columns_to_keep = [
    'FL_DATE', 'DOT_CODE',
    'FL_NUMBER', 'CRS_DEP_TIME',
    'DEP_TIME', 'DEP_DELAY', 'TAXI_OUT', 'WHEELS_OFF', 'CRS_ARR_TIME',
    'ARR_DELAY', 'CRS_ELAPSED_TIME', 'DISTANCE'
]

# Select only the columns you want to keep
fs = fs.loc[:, columns_to_keep]
fs.head(10)

Empty DataFrame
Columns: [FL_DATE, DOT_CODE, FL_NUMBER, CRS_DEP_TIME, DEP_TIME, DEP_DELAY, TAXI_OUT, WHEELS_OFF, CRS_ARR_TIME, ARR_DELAY, CRS_ELAPSED_TIME, DISTANCE]
Index: []

In [118]:
# removing date with year 2020
fs['FL_DATE'] =  pd.to_datetime(fs['FL_DATE'])
#before remove
fs['FL_DATE'].head(10)

Series([], Name: FL_DATE, dtype: datetime64[ns])

In [119]:
fs = fs.loc[fs['FL_DATE'].dt.year != 2020]

In [120]:
#after remove
fs['FL_DATE'].head(10)

Series([], Name: FL_DATE, dtype: datetime64[ns])

In [121]:
fs.head(10)

Empty DataFrame
Columns: [FL_DATE, DOT_CODE, FL_NUMBER, CRS_DEP_TIME, DEP_TIME, DEP_DELAY, TAXI_OUT, WHEELS_OFF, CRS_ARR_TIME, ARR_DELAY, CRS_ELAPSED_TIME, DISTANCE]
Index: []

In [122]:
fs.shape

(0, 12)